### PR TITLE
Allow video.js 8.x

### PR DESCRIPTION
**Pull request by boris-petrov**
Which was forgotten in #606.

cc @gkatsev

### CODE REVIEW

**Comment by boris-petrov** [comment]
Fixes #607

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
Oops, thanks for the ping. Completely forgot.

**Comment by gkatsev** [comment]
Fix published in 3.0.1

**Comment by boris-petrov** [comment]
Thanks!

**Pull request merged**
