### PR TITLE
Fix: Hides poster when the player starts playing.

### PR DESCRIPTION
**Pull request by Krielkip**
Fixes a bug which did not hide the poster when player started to play.

### CODE REVIEW

**Comment by eXon** [comment]
Can you describe a way to replicate? This should not be necessary because as soon as the video is playing, the poster is hidden using CSS classes

**Comment by Krielkip** [comment]
Ofcourse, I am using this with te latest of video-js (v4.11.2) and the recent master.
Using in HTML: 
```
<div class="videoHolder">
 <video id="video-2" src="" class="video-js vjs-default-skin" width="auto" height="auto" poster="img/blocks/instructie/still.jpg" controls preload="auto"  data-setup='{ "techOrder": ["youtube"], "src": "http://www.youtube.com/watch?v=7iZ6GDkQ75o", "playsinline": true, "preload": "auto" }'>
 </video>
</div>
```

video poster CSS:
```
.vjs-poster {
  background-repeat: no-repeat;
  background-position: 50% 50%;
  background-size: contain;
  cursor: pointer;
  margin: 0;
  padding: 0;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
.vjs-poster img {
  display: block;
  margin: 0 auto;
  max-height: 100%;
  padding: 0;
  width: 100%;
}
```

It could be that i came from a older video-js (v4.9.0) and i did not use that css, it worked fine for me. Going to take a look in that.

**Comment by Krielkip** [comment]
Found out that i did not use the following CSS:

```
/* Hide the poster after the video has started playing */
.video-js.vjs-has-started .vjs-poster {
  display: none;
}
```

**Comment by eXon** [comment]
Good to know it only works with the last CSS. Thank you for taking the time to report =)

**Pull request closed without merging**
