### PR TITLE
allow playlist option to use first video

### PR DESCRIPTION
**Pull request by danielma**

### CODE REVIEW

**Comment by eXon** [comment]
When using playlist, if no specific video is specified, it is already choosing the first video and it doesn't need an API key. I don't think this is the way to go, the YouTube iframe API is already giving me that information.

**Comment by danielma** [comment]
Sorry, I guess my description wasn't clear enough. The main thing this pull request adds is the ability to get the video thumbnail for the first video, not just play it

**Comment by eXon** [comment]
It is already getting the thumbnail of the first video. I don't get your point, am I missing something?

**Comment by danielma** [comment]
oh, my mistake. It looks like that was added in d2f0fcf06debb - I made this fork and added this feature before that. I guess it just took me a while to submit the pull request

**Comment by eXon** [comment]
No problem. Thank you for caring enough to do a PR :)

**Pull request closed without merging**
